### ISSUE TITLE
Confusing relation between course-level and activity-level assessment

### ISSUE THREAD

**Issue by mudrd8mz** [StudiUM/moodle-report_cmcompetency#1]
I found the plugin working as expected. However, I am wondering how this will be / is used in production. Particularly, it is confusing for me to be able to use the core's default "Competency breakdown" feature in parallel to this new "Competency assessment". Especially as it is possible (from the teacher's perspective) to rate the same competency in the same activity differently. 

Is there some relation between how competencies are rated using this report and using the standard breakdown report?

**Comment by levemar** [comment]
Hi David, 

You are right : it is confusing. That's why at our university we modified our core to remove the option of the "competency breakdown" from the same menu than our "competency assessment". That's not an ideal situation, but we didn't want our teachers to be confused...

Here is an explanation : Let's say you have Course A with Activity 1 and Activity 2. Competency X is attached to the course and to the 2 activities, and can be rated as "good" or "bad".

Our plugin works this way : The teacher of course A rates a student **activity competencies** with "good" for Act.1 and "bad" for Act.2. Then, he looks at both ratings, and he rates the **course competency** (using core functionnalities) to, let's say "good" for any reason (it doesn't work well with only 2 activities and 2 levels, but the important thing here is that it is his decision).

The core functionnality works this way : In the competency breakdown, the teacher filters the competency for Act.1 and rate it as "good". He than filters for Act.2 and rate it as "bad". The course competency is now "bad", since it keeps the last rating. 

The core competency breakdown makes it possible to **filter** by activity, but you always **rate the course** competency. I guess for some institutions it makes sense, but that is not what we wanted (and I know that other institutions agree with us on this).

**Comment by mudrd8mz** [comment]
> He than filters for Act.2 and rate it as "bad"

Just to clarify. If I understand the core feature correctly, the teacher would already see the competency rated as "good" when he/she comes to rate in the second activity, right?

In either case, I think i start seeing your point and it makes sense. Thank you for your patience explaining this.

**Comment by levemar** [comment]
Exactly. He already sees that it is "Good". But he has that title juste above it "Competencies linked to Activity 1" which may make him think that he is rating the competency for a particular activity, while in fact he only filtered the course competencies to rate it.

**Comment by mudrd8mz** [comment]
Excellent. I understand now. Thank you for clarification.
